version: "3.7"
services:
  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  datasvc:
    build: 
      context: ./go-server
      dockerfile: ./docker/datadocker/Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./go-server
        target: /app
    links:
      - mongo-db
  authsvc:
    build: 
      context: ./go-server
      dockerfile: ./docker/authdocker/Dockerfile.dev
    ports:
      - '8081:8080'
    volumes:
      - type: bind
        source: ./go-server
        target: /app
    links:
      - mongo-db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./react-client
    ports:
      - '3000:3000'
    volumes:
      - ./react-client:/app
      - /app/node_modules
volumes:
  mongo-data:
